// <auto-generated />
using System;
using EntityFramework_Ex_01.Contexts;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace EntityFramework_Ex_01.Migrations
{
    [DbContext(typeof(ProductionContext))]
    [Migration("20220720171332_SeedMigration")]
    partial class SeedMigration
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.17")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("EntityFramework_Ex_01.Models.Actor", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("id");

                    b.ToTable("Actors");

                    b.HasData(
                        new
                        {
                            id = 1,
                            Name = "QQQQQQQ"
                        },
                        new
                        {
                            id = 2,
                            Name = "QQQQQQQ"
                        },
                        new
                        {
                            id = 3,
                            Name = "QQQQQQQ"
                        });
                });

            modelBuilder.Entity("EntityFramework_Ex_01.Models.Character", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("ActorId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("ProductionId")
                        .HasColumnType("int");

                    b.Property<int>("ProfuctionId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ActorId");

                    b.HasIndex("ProductionId");

                    b.ToTable("Characters");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ActorId = 1,
                            Name = "sdgsdg",
                            ProfuctionId = 1
                        },
                        new
                        {
                            Id = 2,
                            ActorId = 2,
                            Name = "sdwwerweg",
                            ProfuctionId = 2
                        },
                        new
                        {
                            Id = 3,
                            ActorId = 3,
                            Name = "s123124dg",
                            ProfuctionId = 1
                        },
                        new
                        {
                            Id = 4,
                            ActorId = 3,
                            Name = "s3254dg",
                            ProfuctionId = 4
                        },
                        new
                        {
                            Id = 5,
                            ActorId = 2,
                            Name = "s35sdg",
                            ProfuctionId = 6
                        },
                        new
                        {
                            Id = 6,
                            ActorId = 1,
                            Name = "sdgs234g",
                            ProfuctionId = 5
                        });
                });

            modelBuilder.Entity("EntityFramework_Ex_01.Models.Production", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Discriminator")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Release")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Productions");

                    b.HasDiscriminator<string>("Discriminator").HasValue("Production");
                });

            modelBuilder.Entity("EntityFramework_Ex_01.Models.Rating", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("ProductionId")
                        .HasColumnType("int");

                    b.Property<string>("Source")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Stars")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ProductionId");

                    b.ToTable("Ratings");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ProductionId = 1,
                            Source = "Group",
                            Stars = 2
                        },
                        new
                        {
                            Id = 2,
                            ProductionId = 1,
                            Source = "Internet",
                            Stars = 1
                        },
                        new
                        {
                            Id = 3,
                            ProductionId = 1,
                            Source = "NewsPapers",
                            Stars = 1
                        },
                        new
                        {
                            Id = 4,
                            ProductionId = 1,
                            Source = "Magazine",
                            Stars = 5
                        },
                        new
                        {
                            Id = 5,
                            ProductionId = 1,
                            Source = "NewsPapers",
                            Stars = 6
                        },
                        new
                        {
                            Id = 6,
                            ProductionId = 1,
                            Source = "Internet",
                            Stars = 7
                        },
                        new
                        {
                            Id = 7,
                            ProductionId = 1,
                            Source = "Magazine",
                            Stars = 7
                        },
                        new
                        {
                            Id = 8,
                            ProductionId = 1,
                            Source = "Group",
                            Stars = 3
                        },
                        new
                        {
                            Id = 9,
                            ProductionId = 1,
                            Source = "Group",
                            Stars = 7
                        },
                        new
                        {
                            Id = 11,
                            ProductionId = 2,
                            Source = "Internet",
                            Stars = 1
                        },
                        new
                        {
                            Id = 12,
                            ProductionId = 2,
                            Source = "Group",
                            Stars = 1
                        },
                        new
                        {
                            Id = 13,
                            ProductionId = 2,
                            Source = "NewsPapers",
                            Stars = 7
                        },
                        new
                        {
                            Id = 14,
                            ProductionId = 2,
                            Source = "Magazine",
                            Stars = 5
                        },
                        new
                        {
                            Id = 15,
                            ProductionId = 2,
                            Source = "NewsPapers",
                            Stars = 4
                        },
                        new
                        {
                            Id = 16,
                            ProductionId = 2,
                            Source = "Magazine",
                            Stars = 5
                        },
                        new
                        {
                            Id = 17,
                            ProductionId = 2,
                            Source = "Group",
                            Stars = 5
                        },
                        new
                        {
                            Id = 18,
                            ProductionId = 2,
                            Source = "Internet",
                            Stars = 1
                        },
                        new
                        {
                            Id = 19,
                            ProductionId = 2,
                            Source = "Group",
                            Stars = 3
                        },
                        new
                        {
                            Id = 21,
                            ProductionId = 3,
                            Source = "NewsPapers",
                            Stars = 4
                        },
                        new
                        {
                            Id = 22,
                            ProductionId = 3,
                            Source = "Magazine",
                            Stars = 4
                        },
                        new
                        {
                            Id = 23,
                            ProductionId = 3,
                            Source = "Group",
                            Stars = 7
                        },
                        new
                        {
                            Id = 24,
                            ProductionId = 3,
                            Source = "Group",
                            Stars = 5
                        },
                        new
                        {
                            Id = 25,
                            ProductionId = 3,
                            Source = "NewsPapers",
                            Stars = 6
                        },
                        new
                        {
                            Id = 26,
                            ProductionId = 3,
                            Source = "Internet",
                            Stars = 1
                        },
                        new
                        {
                            Id = 27,
                            ProductionId = 3,
                            Source = "Magazine",
                            Stars = 4
                        },
                        new
                        {
                            Id = 28,
                            ProductionId = 3,
                            Source = "Group",
                            Stars = 4
                        },
                        new
                        {
                            Id = 29,
                            ProductionId = 3,
                            Source = "Internet",
                            Stars = 1
                        },
                        new
                        {
                            Id = 31,
                            ProductionId = 4,
                            Source = "NewsPapers",
                            Stars = 1
                        },
                        new
                        {
                            Id = 32,
                            ProductionId = 4,
                            Source = "Magazine",
                            Stars = 1
                        },
                        new
                        {
                            Id = 33,
                            ProductionId = 4,
                            Source = "NewsPapers",
                            Stars = 5
                        },
                        new
                        {
                            Id = 34,
                            ProductionId = 4,
                            Source = "NewsPapers",
                            Stars = 6
                        },
                        new
                        {
                            Id = 35,
                            ProductionId = 4,
                            Source = "Internet",
                            Stars = 1
                        },
                        new
                        {
                            Id = 36,
                            ProductionId = 4,
                            Source = "Internet",
                            Stars = 6
                        },
                        new
                        {
                            Id = 37,
                            ProductionId = 4,
                            Source = "Group",
                            Stars = 1
                        },
                        new
                        {
                            Id = 38,
                            ProductionId = 4,
                            Source = "NewsPapers",
                            Stars = 3
                        },
                        new
                        {
                            Id = 39,
                            ProductionId = 4,
                            Source = "Magazine",
                            Stars = 4
                        },
                        new
                        {
                            Id = 41,
                            ProductionId = 5,
                            Source = "NewsPapers",
                            Stars = 4
                        },
                        new
                        {
                            Id = 42,
                            ProductionId = 5,
                            Source = "Internet",
                            Stars = 1
                        },
                        new
                        {
                            Id = 43,
                            ProductionId = 5,
                            Source = "Group",
                            Stars = 2
                        },
                        new
                        {
                            Id = 44,
                            ProductionId = 5,
                            Source = "Internet",
                            Stars = 6
                        },
                        new
                        {
                            Id = 45,
                            ProductionId = 5,
                            Source = "NewsPapers",
                            Stars = 4
                        },
                        new
                        {
                            Id = 46,
                            ProductionId = 5,
                            Source = "Group",
                            Stars = 7
                        },
                        new
                        {
                            Id = 47,
                            ProductionId = 5,
                            Source = "Magazine",
                            Stars = 1
                        },
                        new
                        {
                            Id = 48,
                            ProductionId = 5,
                            Source = "Internet",
                            Stars = 7
                        },
                        new
                        {
                            Id = 49,
                            ProductionId = 5,
                            Source = "Internet",
                            Stars = 1
                        },
                        new
                        {
                            Id = 51,
                            ProductionId = 6,
                            Source = "Group",
                            Stars = 6
                        },
                        new
                        {
                            Id = 52,
                            ProductionId = 6,
                            Source = "Internet",
                            Stars = 6
                        },
                        new
                        {
                            Id = 53,
                            ProductionId = 6,
                            Source = "Magazine",
                            Stars = 5
                        },
                        new
                        {
                            Id = 54,
                            ProductionId = 6,
                            Source = "NewsPapers",
                            Stars = 6
                        },
                        new
                        {
                            Id = 55,
                            ProductionId = 6,
                            Source = "Magazine",
                            Stars = 2
                        },
                        new
                        {
                            Id = 56,
                            ProductionId = 6,
                            Source = "NewsPapers",
                            Stars = 3
                        },
                        new
                        {
                            Id = 57,
                            ProductionId = 6,
                            Source = "Internet",
                            Stars = 5
                        },
                        new
                        {
                            Id = 58,
                            ProductionId = 6,
                            Source = "Group",
                            Stars = 2
                        },
                        new
                        {
                            Id = 59,
                            ProductionId = 6,
                            Source = "Magazine",
                            Stars = 4
                        });
                });

            modelBuilder.Entity("EntityFramework_Ex_01.Models.Movie", b =>
                {
                    b.HasBaseType("EntityFramework_Ex_01.Models.Production");

                    b.Property<int>("DurationInMinutes")
                        .HasColumnType("int");

                    b.Property<int>("WorldWideBoxOfficeGross")
                        .HasColumnType("int");

                    b.HasDiscriminator().HasValue("Movie");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "0000skdngksd",
                            Release = new DateTime(2000, 6, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DurationInMinutes = 190,
                            WorldWideBoxOfficeGross = 20000000
                        },
                        new
                        {
                            Id = 2,
                            Name = "1111sd",
                            Release = new DateTime(2020, 6, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DurationInMinutes = 120,
                            WorldWideBoxOfficeGross = 20000000
                        },
                        new
                        {
                            Id = 3,
                            Name = "2222skdngksd",
                            Release = new DateTime(2010, 6, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DurationInMinutes = 150,
                            WorldWideBoxOfficeGross = 20000000
                        });
                });

            modelBuilder.Entity("EntityFramework_Ex_01.Models.Series", b =>
                {
                    b.HasBaseType("EntityFramework_Ex_01.Models.Production");

                    b.Property<int>("NumberofEpisodes")
                        .HasColumnType("int");

                    b.HasDiscriminator().HasValue("Series");

                    b.HasData(
                        new
                        {
                            Id = 4,
                            Name = "asafsafdasd",
                            Release = new DateTime(2000, 6, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            NumberofEpisodes = 400
                        },
                        new
                        {
                            Id = 5,
                            Name = "asfsdfsd",
                            Release = new DateTime(2000, 6, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            NumberofEpisodes = 4400
                        },
                        new
                        {
                            Id = 6,
                            Name = "a1231234124sd",
                            Release = new DateTime(2100, 6, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            NumberofEpisodes = 400
                        });
                });

            modelBuilder.Entity("EntityFramework_Ex_01.Models.Character", b =>
                {
                    b.HasOne("EntityFramework_Ex_01.Models.Actor", "Actor")
                        .WithMany("Characters")
                        .HasForeignKey("ActorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("EntityFramework_Ex_01.Models.Production", "Production")
                        .WithMany("Character")
                        .HasForeignKey("ProductionId");

                    b.Navigation("Actor");

                    b.Navigation("Production");
                });

            modelBuilder.Entity("EntityFramework_Ex_01.Models.Rating", b =>
                {
                    b.HasOne("EntityFramework_Ex_01.Models.Production", "Production")
                        .WithMany("Rating")
                        .HasForeignKey("ProductionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Production");
                });

            modelBuilder.Entity("EntityFramework_Ex_01.Models.Actor", b =>
                {
                    b.Navigation("Characters");
                });

            modelBuilder.Entity("EntityFramework_Ex_01.Models.Production", b =>
                {
                    b.Navigation("Character");

                    b.Navigation("Rating");
                });
#pragma warning restore 612, 618
        }
    }
}
